# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Install necessary tools and run commands
        brew install fastlane && fastlane unit_test && fastlane generate_code_coverage
  
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'shamiul110107_SwiftUI-Linkedin'
      organization: 'shamiul110107'
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: 'sonar.exclusions=Build/**/*'
  
  - task: SonarCloudAnalyze@1
  
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

  - task: Xcode@5
    inputs:
      actions: 'build'
      scheme: 'YourSchemeName'
      sdk: 'iphoneos'
      configuration: 'Release'
      xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
      xcodeVersion: 'default'

